#!/usr/bin/python

from cutie_shapey import cutie_shapey_py

folder = "LTA Road Map/LTAGDMDR20100914-001/Dover"
road_attributes_shape_name = "%s/RoadAttributeLine_15Sep10_091907" % folder
arrow_markings_shape_name = "%s/ArrowMarking_15Sep10_091855" % folder
kerb_lines_shape_name = "%s/KerbLine_15Sep10_092904" % folder
lane_markings_shape_name = "%s/LaneMarking_15Sep10_091900" % folder
bus_stops_shape_name = "%s/BusStop_15Sep10_091900" % folder
traffic_signals_shape_name = "%s/TrafficSignalAspect_15Sep10_091914" % folder

cutie_shapey_py(road_attributes_shape_name,
                arrow_markings_shape_name,
                kerb_lines_shape_name,
                lane_markings_shape_name,
                bus_stops_shape_name,
                traffic_signals_shape_name)
