#!/usr/bin/env python

# Copyright Singapore-MIT Alliance for Research and Technology

import sys
from PyQt4 import QtGui
# To-do: replace network.py with database.py.
from network import Network
#from database import Network
from view import MainWindow

if len(sys.argv) != 2:
    print "usage: %s siumulator-log-file" % sys.argv[0]
    sys.exit(1)

app = QtGui.QApplication(sys.argv)

input_file = sys.argv[1]
network = Network(input_file)
#network.dump()

window = MainWindow(network)
window.show()

sys.exit(app.exec_())
