// Not copyrighted - public domain.
//
// This sample parser implementation was generated by CodeSynthesis XSD,
// an XML Schema to C++ data binding compiler. You may use it in your
// programs without any restrictions.
//

#include "conf1-pimpl.hpp"

#include <iostream>

using std::string;
using std::pair;


namespace sim_mob
{
  namespace conf
  {

    // driver_explicit_pimpl
    //

    void driver_explicit_pimpl::
    pre ()
    {
    }

    void driver_explicit_pimpl::
    property ()
    {
    }

    void driver_explicit_pimpl::
    originPos (const ::std::string& originPos)
    {
      std::cout << "originPos: " << originPos << std::endl;
    }

    void driver_explicit_pimpl::
    destPos (const ::std::string& destPos)
    {
      std::cout << "destPos: " << destPos << std::endl;
    }

    void driver_explicit_pimpl::
    startTime (const ::std::string& startTime)
    {
      std::cout << "startTime: " << startTime << std::endl;
    }

    void driver_explicit_pimpl::
    startFrame (int startFrame)
    {
      std::cout << "startFrame: " << startFrame << std::endl;
    }

    void driver_explicit_pimpl::
    post_driver_explicit ()
    {
    }

    // drivers_pimpl
    //

    void drivers_pimpl::
    pre ()
    {
    }

    void drivers_pimpl::
    database_loader ()
    {
    }

    void drivers_pimpl::
    xml_loader ()
    {
    }

    void drivers_pimpl::
    driver ()
    {
    }

    void drivers_pimpl::
    post_drivers ()
    {
    }

    // pedestrian_explicit_pimpl
    //

    void pedestrian_explicit_pimpl::
    pre ()
    {
    }

    void pedestrian_explicit_pimpl::
    property ()
    {
    }

    void pedestrian_explicit_pimpl::
    originPos (const ::std::string& originPos)
    {
      std::cout << "originPos: " << originPos << std::endl;
    }

    void pedestrian_explicit_pimpl::
    destPos (const ::std::string& destPos)
    {
      std::cout << "destPos: " << destPos << std::endl;
    }

    void pedestrian_explicit_pimpl::
    startTime (const ::std::string& startTime)
    {
      std::cout << "startTime: " << startTime << std::endl;
    }

    void pedestrian_explicit_pimpl::
    startFrame (int startFrame)
    {
      std::cout << "startFrame: " << startFrame << std::endl;
    }

    void pedestrian_explicit_pimpl::
    post_pedestrian_explicit ()
    {
    }

    // pedestrians_pimpl
    //

    void pedestrians_pimpl::
    pre ()
    {
    }

    void pedestrians_pimpl::
    database_loader ()
    {
    }

    void pedestrians_pimpl::
    xml_loader ()
    {
    }

    void pedestrians_pimpl::
    pedestrian ()
    {
    }

    void pedestrians_pimpl::
    post_pedestrians ()
    {
    }

    // busdrivers_pimpl
    //

    void busdrivers_pimpl::
    pre ()
    {
    }

    void busdrivers_pimpl::
    database_loader ()
    {
    }

    void busdrivers_pimpl::
    xml_loader ()
    {
    }

    void busdrivers_pimpl::
    post_busdrivers ()
    {
    }

    // constructs_pimpl
    //

    void constructs_pimpl::
    pre ()
    {
    }

    void constructs_pimpl::
    models ()
    {
    }

    void constructs_pimpl::
    workgroups ()
    {
    }

    void constructs_pimpl::
    distributions ()
    {
    }

    void constructs_pimpl::
    db_connections ()
    {
    }

    void constructs_pimpl::
    db_proc_groups ()
    {
    }

    void constructs_pimpl::
    post_constructs ()
    {
    }

    // system_pimpl
    //

    void system_pimpl::
    pre ()
    {
    }

    void system_pimpl::
    default_models ()
    {
    }

    void system_pimpl::
    workgroup_mappings ()
    {
    }

    void system_pimpl::
    generic_props ()
    {
    }

    void system_pimpl::
    post_system ()
    {
    }

    // simulation_pimpl
    //

    void simulation_pimpl::
    pre ()
    {
    }

    void simulation_pimpl::
    base_granularity ()
    {
    }

    void simulation_pimpl::
    total_runtime ()
    {
    }

    void simulation_pimpl::
    total_warmup ()
    {
    }

    void simulation_pimpl::
    start_time ()
    {
    }

    void simulation_pimpl::
    granularities ()
    {
    }

    void simulation_pimpl::
    react_times ()
    {
    }

    void simulation_pimpl::
    geospatial ()
    {
    }

    void simulation_pimpl::
    agents ()
    {
    }

    void simulation_pimpl::
    post_simulation ()
    {
    }

    // SimMobility_pimpl
    //

    void SimMobility_pimpl::
    pre ()
    {
    }

    void SimMobility_pimpl::
    constructs ()
    {
    }

    void SimMobility_pimpl::
    single_threaded (bool single_threaded)
    {
      std::cout << "single_threaded: " << single_threaded << std::endl;
    }

    void SimMobility_pimpl::
    system ()
    {
    }

    void SimMobility_pimpl::
    simulation ()
    {
    }

    void SimMobility_pimpl::
    post_SimMobility ()
    {
    }

    // models_pimpl
    //

    void models_pimpl::
    pre ()
    {
    }

    void models_pimpl::
    lane_changing (const pair<string, string>&)
    {
    }

    void models_pimpl::
    car_following (const pair<string, string>&)
    {
    }

    void models_pimpl::
    intersection_driving (const pair<string, string>&)
    {
    }

    void models_pimpl::
    sidewalk_movement (const pair<string, string>&)
    {
    }

    void models_pimpl::
    post_models ()
    {
    }

    // workgroups_pimpl
    //

    void workgroups_pimpl::
    pre ()
    {
    }

    void workgroups_pimpl::
    workgroup ()
    {
    }

    void workgroups_pimpl::
    post_workgroups ()
    {
    }

    // distributions_pimpl
    //

    void distributions_pimpl::
    pre ()
    {
    }

    void distributions_pimpl::
    dist ()
    {
    }

    void distributions_pimpl::
    post_distributions ()
    {
    }

    // db_connections_pimpl
    //

    void db_connections_pimpl::
    pre ()
    {
    }

    void db_connections_pimpl::
    connection ()
    {
    }

    void db_connections_pimpl::
    post_db_connections ()
    {
    }

    // db_proc_groups_pimpl
    //

    void db_proc_groups_pimpl::
    pre ()
    {
    }

    void db_proc_groups_pimpl::
    proc_map ()
    {
    }

    void db_proc_groups_pimpl::
    post_db_proc_groups ()
    {
    }

    // default_models_pimpl
    //

    void default_models_pimpl::
    pre ()
    {
    }

    void default_models_pimpl::
    model ()
    {
    }

    void default_models_pimpl::
    post_default_models ()
    {
    }

    // workgroup_mappings_pimpl
    //

    void workgroup_mappings_pimpl::
    pre ()
    {
    }

    void workgroup_mappings_pimpl::
    agents ()
    {
    }

    void workgroup_mappings_pimpl::
    signals ()
    {
    }

    void workgroup_mappings_pimpl::
    post_workgroup_mappings ()
    {
    }

    // generic_props_pimpl
    //

    void generic_props_pimpl::
    pre ()
    {
    }

    void generic_props_pimpl::
    property ()
    {
    }

    void generic_props_pimpl::
    post_generic_props ()
    {
    }

    // start_time_pimpl
    //

    void start_time_pimpl::
    pre ()
    {
    }

    void start_time_pimpl::
    value (const ::std::string& value)
    {
      std::cout << "value: " << value << std::endl;
    }

    void start_time_pimpl::
    post_start_time ()
    {
    }

    // granularities_pimpl
    //

    void granularities_pimpl::
    pre ()
    {
    }

    void granularities_pimpl::
    agent ()
    {
    }

    void granularities_pimpl::
    signal ()
    {
    }

    void granularities_pimpl::
    post_granularities ()
    {
    }

    // react_times_pimpl
    //

    void react_times_pimpl::
    pre ()
    {
    }

    void react_times_pimpl::
    leading_vehicle ()
    {
    }

    void react_times_pimpl::
    subject_vehicle ()
    {
    }

    void react_times_pimpl::
    vehicle_gap ()
    {
    }

    void react_times_pimpl::
    post_react_times ()
    {
    }

    // geospatial_pimpl
    //

    void geospatial_pimpl::
    pre ()
    {
    }

    void geospatial_pimpl::
    road_network ()
    {
    }

    void geospatial_pimpl::
    post_geospatial ()
    {
    }

    // agents_pimpl
    //

    void agents_pimpl::
    pre ()
    {
    }

    void agents_pimpl::
    trip_chains ()
    {
    }

    void agents_pimpl::
    signals ()
    {
    }

    void agents_pimpl::
    drivers ()
    {
    }

    void agents_pimpl::
    pedestrians ()
    {
    }

    void agents_pimpl::
    busdrivers ()
    {
    }

    void agents_pimpl::
    post_agents ()
    {
    }
  }
}

