// Copyright (C) 2005-2010 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis Tools CC gives
// permission to link this program with the Xerces-C++ library (or with
// modified versions of Xerces-C++ that use the same license as Xerces-C++),
// and distribute linked combinations including the two. You must obey
// the GNU General Public License version 2 in all respects for all of
// the code used other than Xerces-C++. If you modify this copy of the
// program, you may extend this exception to your version of the program,
// but you are not obligated to do so. If you do not wish to do so, delete
// this exception statement from your version.
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

#ifndef CONF1_PSKEL_HPP
#define CONF1_PSKEL_HPP

// Begin prologue.
//
// NOTE: Do *not* edit the -pskel.* files; they are generated automatically from the xsd file. 
//       Instead, modify the -pimpl.* files. ~Seth
//
// End prologue.

#include <xsd/cxx/config.hxx>

#if (XSD_INT_VERSION != 3030000L)
#error XSD runtime version mismatch
#endif

#include <xsd/cxx/pre.hxx>

// Forward declarations
//
namespace sim_mob
{
  namespace conf
  {
    class model_pskel;
    class workgroup_pskel;
    class reaction_time_pskel;
    class db_connection_pskel;
    class db_param_pskel;
    class db_proc_mapping_pskel;
    class proc_map_pskel;
    class constructs_pskel;
    class SimMobility_pskel;
    class models_pskel;
    class workgroup_sizes_pskel;
    class react_times_pskel;
    class db_connections_pskel;
    class db_proc_groups_pskel;
  }
}


#ifndef XSD_USE_CHAR
#define XSD_USE_CHAR
#endif

#ifndef XSD_CXX_PARSER_USE_CHAR
#define XSD_CXX_PARSER_USE_CHAR
#endif

#include <xsd/cxx/xml/char-utf8.hxx>
#include <xsd/cxx/xml/error-handler.hxx>
#include <xsd/cxx/parser/exceptions.hxx>
#include <xsd/cxx/parser/elements.hxx>
#include <xsd/cxx/parser/xml-schema.hxx>
#include <xsd/cxx/parser/non-validating/parser.hxx>
#include <xsd/cxx/parser/non-validating/xml-schema-pskel.hxx>
#include <xsd/cxx/parser/non-validating/xml-schema-pimpl.hxx>
#include <xsd/cxx/parser/xerces/elements.hxx>

namespace xml_schema
{
  // Built-in XML Schema types mapping.
  //
  typedef ::xsd::cxx::parser::string_sequence< char > string_sequence;
  typedef ::xsd::cxx::parser::qname< char > qname;
  typedef ::xsd::cxx::parser::buffer buffer;
  typedef ::xsd::cxx::parser::time_zone time_zone;
  typedef ::xsd::cxx::parser::gday gday;
  typedef ::xsd::cxx::parser::gmonth gmonth;
  typedef ::xsd::cxx::parser::gyear gyear;
  typedef ::xsd::cxx::parser::gmonth_day gmonth_day;
  typedef ::xsd::cxx::parser::gyear_month gyear_month;
  typedef ::xsd::cxx::parser::date date;
  typedef ::xsd::cxx::parser::time time;
  typedef ::xsd::cxx::parser::date_time date_time;
  typedef ::xsd::cxx::parser::duration duration;

  // Base parser skeletons.
  //
  typedef ::xsd::cxx::parser::parser_base< char > parser_base;
  typedef ::xsd::cxx::parser::non_validating::empty_content< char > empty_content;
  typedef ::xsd::cxx::parser::non_validating::simple_content< char > simple_content;
  typedef ::xsd::cxx::parser::non_validating::complex_content< char > complex_content;
  typedef ::xsd::cxx::parser::non_validating::list_base< char > list_base;

  // Parser skeletons and implementations for the XML Schema
  // built-in types.
  //
  typedef ::xsd::cxx::parser::non_validating::any_type_pskel< char > any_type_pskel;
  typedef ::xsd::cxx::parser::non_validating::any_type_pimpl< char > any_type_pimpl;

  typedef ::xsd::cxx::parser::non_validating::any_simple_type_pskel< char > any_simple_type_pskel;
  typedef ::xsd::cxx::parser::non_validating::any_simple_type_pimpl< char > any_simple_type_pimpl;

  typedef ::xsd::cxx::parser::non_validating::byte_pskel< char > byte_pskel;
  typedef ::xsd::cxx::parser::non_validating::byte_pimpl< char > byte_pimpl;

  typedef ::xsd::cxx::parser::non_validating::unsigned_byte_pskel< char > unsigned_byte_pskel;
  typedef ::xsd::cxx::parser::non_validating::unsigned_byte_pimpl< char > unsigned_byte_pimpl;

  typedef ::xsd::cxx::parser::non_validating::short_pskel< char > short_pskel;
  typedef ::xsd::cxx::parser::non_validating::short_pimpl< char > short_pimpl;

  typedef ::xsd::cxx::parser::non_validating::unsigned_short_pskel< char > unsigned_short_pskel;
  typedef ::xsd::cxx::parser::non_validating::unsigned_short_pimpl< char > unsigned_short_pimpl;

  typedef ::xsd::cxx::parser::non_validating::int_pskel< char > int_pskel;
  typedef ::xsd::cxx::parser::non_validating::int_pimpl< char > int_pimpl;

  typedef ::xsd::cxx::parser::non_validating::unsigned_int_pskel< char > unsigned_int_pskel;
  typedef ::xsd::cxx::parser::non_validating::unsigned_int_pimpl< char > unsigned_int_pimpl;

  typedef ::xsd::cxx::parser::non_validating::long_pskel< char > long_pskel;
  typedef ::xsd::cxx::parser::non_validating::long_pimpl< char > long_pimpl;

  typedef ::xsd::cxx::parser::non_validating::unsigned_long_pskel< char > unsigned_long_pskel;
  typedef ::xsd::cxx::parser::non_validating::unsigned_long_pimpl< char > unsigned_long_pimpl;

  typedef ::xsd::cxx::parser::non_validating::integer_pskel< char > integer_pskel;
  typedef ::xsd::cxx::parser::non_validating::integer_pimpl< char > integer_pimpl;

  typedef ::xsd::cxx::parser::non_validating::non_positive_integer_pskel< char > non_positive_integer_pskel;
  typedef ::xsd::cxx::parser::non_validating::non_positive_integer_pimpl< char > non_positive_integer_pimpl;

  typedef ::xsd::cxx::parser::non_validating::non_negative_integer_pskel< char > non_negative_integer_pskel;
  typedef ::xsd::cxx::parser::non_validating::non_negative_integer_pimpl< char > non_negative_integer_pimpl;

  typedef ::xsd::cxx::parser::non_validating::positive_integer_pskel< char > positive_integer_pskel;
  typedef ::xsd::cxx::parser::non_validating::positive_integer_pimpl< char > positive_integer_pimpl;

  typedef ::xsd::cxx::parser::non_validating::negative_integer_pskel< char > negative_integer_pskel;
  typedef ::xsd::cxx::parser::non_validating::negative_integer_pimpl< char > negative_integer_pimpl;

  typedef ::xsd::cxx::parser::non_validating::boolean_pskel< char > boolean_pskel;
  typedef ::xsd::cxx::parser::non_validating::boolean_pimpl< char > boolean_pimpl;

  typedef ::xsd::cxx::parser::non_validating::float_pskel< char > float_pskel;
  typedef ::xsd::cxx::parser::non_validating::float_pimpl< char > float_pimpl;

  typedef ::xsd::cxx::parser::non_validating::double_pskel< char > double_pskel;
  typedef ::xsd::cxx::parser::non_validating::double_pimpl< char > double_pimpl;

  typedef ::xsd::cxx::parser::non_validating::decimal_pskel< char > decimal_pskel;
  typedef ::xsd::cxx::parser::non_validating::decimal_pimpl< char > decimal_pimpl;

  typedef ::xsd::cxx::parser::non_validating::string_pskel< char > string_pskel;
  typedef ::xsd::cxx::parser::non_validating::string_pimpl< char > string_pimpl;

  typedef ::xsd::cxx::parser::non_validating::normalized_string_pskel< char > normalized_string_pskel;
  typedef ::xsd::cxx::parser::non_validating::normalized_string_pimpl< char > normalized_string_pimpl;

  typedef ::xsd::cxx::parser::non_validating::token_pskel< char > token_pskel;
  typedef ::xsd::cxx::parser::non_validating::token_pimpl< char > token_pimpl;

  typedef ::xsd::cxx::parser::non_validating::name_pskel< char > name_pskel;
  typedef ::xsd::cxx::parser::non_validating::name_pimpl< char > name_pimpl;

  typedef ::xsd::cxx::parser::non_validating::nmtoken_pskel< char > nmtoken_pskel;
  typedef ::xsd::cxx::parser::non_validating::nmtoken_pimpl< char > nmtoken_pimpl;

  typedef ::xsd::cxx::parser::non_validating::nmtokens_pskel< char > nmtokens_pskel;
  typedef ::xsd::cxx::parser::non_validating::nmtokens_pimpl< char > nmtokens_pimpl;

  typedef ::xsd::cxx::parser::non_validating::ncname_pskel< char > ncname_pskel;
  typedef ::xsd::cxx::parser::non_validating::ncname_pimpl< char > ncname_pimpl;

  typedef ::xsd::cxx::parser::non_validating::language_pskel< char > language_pskel;
  typedef ::xsd::cxx::parser::non_validating::language_pimpl< char > language_pimpl;

  typedef ::xsd::cxx::parser::non_validating::id_pskel< char > id_pskel;
  typedef ::xsd::cxx::parser::non_validating::id_pimpl< char > id_pimpl;

  typedef ::xsd::cxx::parser::non_validating::idref_pskel< char > idref_pskel;
  typedef ::xsd::cxx::parser::non_validating::idref_pimpl< char > idref_pimpl;

  typedef ::xsd::cxx::parser::non_validating::idrefs_pskel< char > idrefs_pskel;
  typedef ::xsd::cxx::parser::non_validating::idrefs_pimpl< char > idrefs_pimpl;

  typedef ::xsd::cxx::parser::non_validating::uri_pskel< char > uri_pskel;
  typedef ::xsd::cxx::parser::non_validating::uri_pimpl< char > uri_pimpl;

  typedef ::xsd::cxx::parser::non_validating::qname_pskel< char > qname_pskel;
  typedef ::xsd::cxx::parser::non_validating::qname_pimpl< char > qname_pimpl;

  typedef ::xsd::cxx::parser::non_validating::base64_binary_pskel< char > base64_binary_pskel;
  typedef ::xsd::cxx::parser::non_validating::base64_binary_pimpl< char > base64_binary_pimpl;

  typedef ::xsd::cxx::parser::non_validating::hex_binary_pskel< char > hex_binary_pskel;
  typedef ::xsd::cxx::parser::non_validating::hex_binary_pimpl< char > hex_binary_pimpl;

  typedef ::xsd::cxx::parser::non_validating::date_pskel< char > date_pskel;
  typedef ::xsd::cxx::parser::non_validating::date_pimpl< char > date_pimpl;

  typedef ::xsd::cxx::parser::non_validating::date_time_pskel< char > date_time_pskel;
  typedef ::xsd::cxx::parser::non_validating::date_time_pimpl< char > date_time_pimpl;

  typedef ::xsd::cxx::parser::non_validating::duration_pskel< char > duration_pskel;
  typedef ::xsd::cxx::parser::non_validating::duration_pimpl< char > duration_pimpl;

  typedef ::xsd::cxx::parser::non_validating::gday_pskel< char > gday_pskel;
  typedef ::xsd::cxx::parser::non_validating::gday_pimpl< char > gday_pimpl;

  typedef ::xsd::cxx::parser::non_validating::gmonth_pskel< char > gmonth_pskel;
  typedef ::xsd::cxx::parser::non_validating::gmonth_pimpl< char > gmonth_pimpl;

  typedef ::xsd::cxx::parser::non_validating::gmonth_day_pskel< char > gmonth_day_pskel;
  typedef ::xsd::cxx::parser::non_validating::gmonth_day_pimpl< char > gmonth_day_pimpl;

  typedef ::xsd::cxx::parser::non_validating::gyear_pskel< char > gyear_pskel;
  typedef ::xsd::cxx::parser::non_validating::gyear_pimpl< char > gyear_pimpl;

  typedef ::xsd::cxx::parser::non_validating::gyear_month_pskel< char > gyear_month_pskel;
  typedef ::xsd::cxx::parser::non_validating::gyear_month_pimpl< char > gyear_month_pimpl;

  typedef ::xsd::cxx::parser::non_validating::time_pskel< char > time_pskel;
  typedef ::xsd::cxx::parser::non_validating::time_pimpl< char > time_pimpl;

  // Exceptions. See libxsd/xsd/cxx/parser/exceptions.hxx for details.
  //
  typedef ::xsd::cxx::parser::exception< char > exception;

  // Parsing diagnostics.
  //
  typedef ::xsd::cxx::parser::severity severity;
  typedef ::xsd::cxx::parser::error< char > error;
  typedef ::xsd::cxx::parser::diagnostics< char > diagnostics;
  typedef ::xsd::cxx::parser::parsing< char > parsing;

  // Error handler. See libxsd/xsd/cxx/xml/error-handler.hxx for details.
  //
  typedef ::xsd::cxx::xml::error_handler< char > error_handler;

  // Read-only string.
  //
  typedef ::xsd::cxx::ro_string< char > ro_string;

  // Parsing flags. See libxsd/xsd/cxx/parser/xerces/elements.hxx
  // for details.
  //
  typedef ::xsd::cxx::parser::xerces::flags flags;

  // Parsing properties. See libxsd/xsd/cxx/parser/xerces/elements.hxx
  // for details.
  //
  typedef ::xsd::cxx::parser::xerces::properties< char > properties;

  // Document type. See libxsd/xsd/cxx/parser/xerces/elements.hxx
  // for details.
  //
  typedef ::xsd::cxx::parser::xerces::document< char > document;
}

namespace sim_mob
{
  namespace conf
  {
    class model_pskel: public ::xml_schema::complex_content
    {
      public:
      // Parser callbacks. Override them in your implementation.
      //
      // virtual void
      // pre ();

      virtual void
      id (const ::std::string&);

      virtual void
      library (const ::std::string&);

      virtual void
      post_model ();

      // Parser construction API.
      //
      void
      id_parser (::xml_schema::string_pskel&);

      void
      library_parser (::xml_schema::string_pskel&);

      void
      parsers (::xml_schema::string_pskel& /* id */,
               ::xml_schema::string_pskel& /* library */);

      // Constructor.
      //
      model_pskel ();

      // Implementation.
      //
      protected:
      virtual bool
      _attribute_impl (const ::xml_schema::ro_string&,
                       const ::xml_schema::ro_string&,
                       const ::xml_schema::ro_string&);

      protected:
      ::xml_schema::string_pskel* id_parser_;
      ::xml_schema::string_pskel* library_parser_;
    };

    class workgroup_pskel: public ::xml_schema::complex_content
    {
      public:
      // Parser callbacks. Override them in your implementation.
      //
      // virtual void
      // pre ();

      virtual void
      value (int);

      virtual void
      post_workgroup ();

      // Parser construction API.
      //
      void
      value_parser (::xml_schema::int_pskel&);

      void
      parsers (::xml_schema::int_pskel& /* value */);

      // Constructor.
      //
      workgroup_pskel ();

      // Implementation.
      //
      protected:
      virtual bool
      _attribute_impl (const ::xml_schema::ro_string&,
                       const ::xml_schema::ro_string&,
                       const ::xml_schema::ro_string&);

      protected:
      ::xml_schema::int_pskel* value_parser_;
    };

    class reaction_time_pskel: public ::xml_schema::complex_content
    {
      public:
      // Parser callbacks. Override them in your implementation.
      //
      // virtual void
      // pre ();

      virtual void
      type (const ::std::string&);

      virtual void
      mean (int);

      virtual void
      stdev (int);

      virtual void
      post_reaction_time ();

      // Parser construction API.
      //
      void
      type_parser (::xml_schema::string_pskel&);

      void
      mean_parser (::xml_schema::int_pskel&);

      void
      stdev_parser (::xml_schema::int_pskel&);

      void
      parsers (::xml_schema::string_pskel& /* type */,
               ::xml_schema::int_pskel& /* mean */,
               ::xml_schema::int_pskel& /* stdev */);

      // Constructor.
      //
      reaction_time_pskel ();

      // Implementation.
      //
      protected:
      virtual bool
      _attribute_impl (const ::xml_schema::ro_string&,
                       const ::xml_schema::ro_string&,
                       const ::xml_schema::ro_string&);

      protected:
      ::xml_schema::string_pskel* type_parser_;
      ::xml_schema::int_pskel* mean_parser_;
      ::xml_schema::int_pskel* stdev_parser_;
    };

    class db_connection_pskel: public ::xml_schema::complex_content
    {
      public:
      // Parser callbacks. Override them in your implementation.
      //
      // virtual void
      // pre ();

      virtual void
      param ();

      virtual void
      id (const ::std::string&);

      virtual void
      dbtype (const ::std::string&);

      virtual void
      post_db_connection ();

      // Parser construction API.
      //
      void
      param_parser (::sim_mob::conf::db_param_pskel&);

      void
      id_parser (::xml_schema::string_pskel&);

      void
      dbtype_parser (::xml_schema::string_pskel&);

      void
      parsers (::sim_mob::conf::db_param_pskel& /* param */,
               ::xml_schema::string_pskel& /* id */,
               ::xml_schema::string_pskel& /* dbtype */);

      // Constructor.
      //
      db_connection_pskel ();

      // Implementation.
      //
      protected:
      virtual bool
      _start_element_impl (const ::xml_schema::ro_string&,
                           const ::xml_schema::ro_string&,
                           const ::xml_schema::ro_string*);

      virtual bool
      _end_element_impl (const ::xml_schema::ro_string&,
                         const ::xml_schema::ro_string&);

      virtual bool
      _attribute_impl (const ::xml_schema::ro_string&,
                       const ::xml_schema::ro_string&,
                       const ::xml_schema::ro_string&);

      protected:
      ::sim_mob::conf::db_param_pskel* param_parser_;
      ::xml_schema::string_pskel* id_parser_;
      ::xml_schema::string_pskel* dbtype_parser_;
    };

    class db_param_pskel: public ::xml_schema::complex_content
    {
      public:
      // Parser callbacks. Override them in your implementation.
      //
      // virtual void
      // pre ();

      virtual void
      name (const ::std::string&);

      virtual void
      value (const ::std::string&);

      virtual void
      post_db_param ();

      // Parser construction API.
      //
      void
      name_parser (::xml_schema::string_pskel&);

      void
      value_parser (::xml_schema::string_pskel&);

      void
      parsers (::xml_schema::string_pskel& /* name */,
               ::xml_schema::string_pskel& /* value */);

      // Constructor.
      //
      db_param_pskel ();

      // Implementation.
      //
      protected:
      virtual bool
      _attribute_impl (const ::xml_schema::ro_string&,
                       const ::xml_schema::ro_string&,
                       const ::xml_schema::ro_string&);

      protected:
      ::xml_schema::string_pskel* name_parser_;
      ::xml_schema::string_pskel* value_parser_;
    };

    class db_proc_mapping_pskel: public ::xml_schema::complex_content
    {
      public:
      // Parser callbacks. Override them in your implementation.
      //
      // virtual void
      // pre ();

      virtual void
      name (const ::std::string&);

      virtual void
      procedure (const ::std::string&);

      virtual void
      post_db_proc_mapping ();

      // Parser construction API.
      //
      void
      name_parser (::xml_schema::string_pskel&);

      void
      procedure_parser (::xml_schema::string_pskel&);

      void
      parsers (::xml_schema::string_pskel& /* name */,
               ::xml_schema::string_pskel& /* procedure */);

      // Constructor.
      //
      db_proc_mapping_pskel ();

      // Implementation.
      //
      protected:
      virtual bool
      _attribute_impl (const ::xml_schema::ro_string&,
                       const ::xml_schema::ro_string&,
                       const ::xml_schema::ro_string&);

      protected:
      ::xml_schema::string_pskel* name_parser_;
      ::xml_schema::string_pskel* procedure_parser_;
    };

    class proc_map_pskel: public ::xml_schema::complex_content
    {
      public:
      // Parser callbacks. Override them in your implementation.
      //
      // virtual void
      // pre ();

      virtual void
      mapping ();

      virtual void
      id (const ::std::string&);

      virtual void
      format (const ::std::string&);

      virtual void
      post_proc_map ();

      // Parser construction API.
      //
      void
      mapping_parser (::sim_mob::conf::db_proc_mapping_pskel&);

      void
      id_parser (::xml_schema::string_pskel&);

      void
      format_parser (::xml_schema::string_pskel&);

      void
      parsers (::sim_mob::conf::db_proc_mapping_pskel& /* mapping */,
               ::xml_schema::string_pskel& /* id */,
               ::xml_schema::string_pskel& /* format */);

      // Constructor.
      //
      proc_map_pskel ();

      // Implementation.
      //
      protected:
      virtual bool
      _start_element_impl (const ::xml_schema::ro_string&,
                           const ::xml_schema::ro_string&,
                           const ::xml_schema::ro_string*);

      virtual bool
      _end_element_impl (const ::xml_schema::ro_string&,
                         const ::xml_schema::ro_string&);

      virtual bool
      _attribute_impl (const ::xml_schema::ro_string&,
                       const ::xml_schema::ro_string&,
                       const ::xml_schema::ro_string&);

      protected:
      ::sim_mob::conf::db_proc_mapping_pskel* mapping_parser_;
      ::xml_schema::string_pskel* id_parser_;
      ::xml_schema::string_pskel* format_parser_;
    };

    class constructs_pskel: public ::xml_schema::complex_content
    {
      public:
      // Parser callbacks. Override them in your implementation.
      //
      // virtual void
      // pre ();

      virtual void
      models ();

      virtual void
      workgroup_sizes ();

      virtual void
      react_times ();

      virtual void
      db_connections ();

      virtual void
      db_proc_groups ();

      virtual void
      post_constructs ();

      // Parser construction API.
      //
      void
      models_parser (::sim_mob::conf::models_pskel&);

      void
      workgroup_sizes_parser (::sim_mob::conf::workgroup_sizes_pskel&);

      void
      react_times_parser (::sim_mob::conf::react_times_pskel&);

      void
      db_connections_parser (::sim_mob::conf::db_connections_pskel&);

      void
      db_proc_groups_parser (::sim_mob::conf::db_proc_groups_pskel&);

      void
      parsers (::sim_mob::conf::models_pskel& /* models */,
               ::sim_mob::conf::workgroup_sizes_pskel& /* workgroup_sizes */,
               ::sim_mob::conf::react_times_pskel& /* react_times */,
               ::sim_mob::conf::db_connections_pskel& /* db_connections */,
               ::sim_mob::conf::db_proc_groups_pskel& /* db_proc_groups */);

      // Constructor.
      //
      constructs_pskel ();

      // Implementation.
      //
      protected:
      virtual bool
      _start_element_impl (const ::xml_schema::ro_string&,
                           const ::xml_schema::ro_string&,
                           const ::xml_schema::ro_string*);

      virtual bool
      _end_element_impl (const ::xml_schema::ro_string&,
                         const ::xml_schema::ro_string&);

      protected:
      ::sim_mob::conf::models_pskel* models_parser_;
      ::sim_mob::conf::workgroup_sizes_pskel* workgroup_sizes_parser_;
      ::sim_mob::conf::react_times_pskel* react_times_parser_;
      ::sim_mob::conf::db_connections_pskel* db_connections_parser_;
      ::sim_mob::conf::db_proc_groups_pskel* db_proc_groups_parser_;
    };

    class SimMobility_pskel: public ::xml_schema::complex_content
    {
      public:
      // Parser callbacks. Override them in your implementation.
      //
      // virtual void
      // pre ();

      virtual void
      constructs ();

      virtual void
      post_SimMobility ();

      // Parser construction API.
      //
      void
      constructs_parser (::sim_mob::conf::constructs_pskel&);

      void
      parsers (::sim_mob::conf::constructs_pskel& /* constructs */);

      // Constructor.
      //
      SimMobility_pskel ();

      // Implementation.
      //
      protected:
      virtual bool
      _start_element_impl (const ::xml_schema::ro_string&,
                           const ::xml_schema::ro_string&,
                           const ::xml_schema::ro_string*);

      virtual bool
      _end_element_impl (const ::xml_schema::ro_string&,
                         const ::xml_schema::ro_string&);

      protected:
      ::sim_mob::conf::constructs_pskel* constructs_parser_;
    };

    class models_pskel: public ::xml_schema::complex_content
    {
      public:
      // Parser callbacks. Override them in your implementation.
      //
      // virtual void
      // pre ();

      virtual void
      lane_changing ();

      virtual void
      car_following ();

      virtual void
      intersection_driving ();

      virtual void
      sidewalk_movement ();

      virtual void
      post_models ();

      // Parser construction API.
      //
      void
      lane_changing_parser (::sim_mob::conf::model_pskel&);

      void
      car_following_parser (::sim_mob::conf::model_pskel&);

      void
      intersection_driving_parser (::sim_mob::conf::model_pskel&);

      void
      sidewalk_movement_parser (::sim_mob::conf::model_pskel&);

      void
      parsers (::sim_mob::conf::model_pskel& /* lane_changing */,
               ::sim_mob::conf::model_pskel& /* car_following */,
               ::sim_mob::conf::model_pskel& /* intersection_driving */,
               ::sim_mob::conf::model_pskel& /* sidewalk_movement */);

      // Constructor.
      //
      models_pskel ();

      // Implementation.
      //
      protected:
      virtual bool
      _start_element_impl (const ::xml_schema::ro_string&,
                           const ::xml_schema::ro_string&,
                           const ::xml_schema::ro_string*);

      virtual bool
      _end_element_impl (const ::xml_schema::ro_string&,
                         const ::xml_schema::ro_string&);

      protected:
      ::sim_mob::conf::model_pskel* lane_changing_parser_;
      ::sim_mob::conf::model_pskel* car_following_parser_;
      ::sim_mob::conf::model_pskel* intersection_driving_parser_;
      ::sim_mob::conf::model_pskel* sidewalk_movement_parser_;
    };

    class workgroup_sizes_pskel: public ::xml_schema::complex_content
    {
      public:
      // Parser callbacks. Override them in your implementation.
      //
      // virtual void
      // pre ();

      virtual void
      agent ();

      virtual void
      signal ();

      virtual void
      post_workgroup_sizes ();

      // Parser construction API.
      //
      void
      agent_parser (::sim_mob::conf::workgroup_pskel&);

      void
      signal_parser (::sim_mob::conf::workgroup_pskel&);

      void
      parsers (::sim_mob::conf::workgroup_pskel& /* agent */,
               ::sim_mob::conf::workgroup_pskel& /* signal */);

      // Constructor.
      //
      workgroup_sizes_pskel ();

      // Implementation.
      //
      protected:
      virtual bool
      _start_element_impl (const ::xml_schema::ro_string&,
                           const ::xml_schema::ro_string&,
                           const ::xml_schema::ro_string*);

      virtual bool
      _end_element_impl (const ::xml_schema::ro_string&,
                         const ::xml_schema::ro_string&);

      protected:
      ::sim_mob::conf::workgroup_pskel* agent_parser_;
      ::sim_mob::conf::workgroup_pskel* signal_parser_;
    };

    class react_times_pskel: public ::xml_schema::complex_content
    {
      public:
      // Parser callbacks. Override them in your implementation.
      //
      // virtual void
      // pre ();

      virtual void
      dist1 ();

      virtual void
      dist2 ();

      virtual void
      post_react_times ();

      // Parser construction API.
      //
      void
      dist1_parser (::sim_mob::conf::reaction_time_pskel&);

      void
      dist2_parser (::sim_mob::conf::reaction_time_pskel&);

      void
      parsers (::sim_mob::conf::reaction_time_pskel& /* dist1 */,
               ::sim_mob::conf::reaction_time_pskel& /* dist2 */);

      // Constructor.
      //
      react_times_pskel ();

      // Implementation.
      //
      protected:
      virtual bool
      _start_element_impl (const ::xml_schema::ro_string&,
                           const ::xml_schema::ro_string&,
                           const ::xml_schema::ro_string*);

      virtual bool
      _end_element_impl (const ::xml_schema::ro_string&,
                         const ::xml_schema::ro_string&);

      protected:
      ::sim_mob::conf::reaction_time_pskel* dist1_parser_;
      ::sim_mob::conf::reaction_time_pskel* dist2_parser_;
    };

    class db_connections_pskel: public ::xml_schema::complex_content
    {
      public:
      // Parser callbacks. Override them in your implementation.
      //
      // virtual void
      // pre ();

      virtual void
      connection ();

      virtual void
      post_db_connections ();

      // Parser construction API.
      //
      void
      connection_parser (::sim_mob::conf::db_connection_pskel&);

      void
      parsers (::sim_mob::conf::db_connection_pskel& /* connection */);

      // Constructor.
      //
      db_connections_pskel ();

      // Implementation.
      //
      protected:
      virtual bool
      _start_element_impl (const ::xml_schema::ro_string&,
                           const ::xml_schema::ro_string&,
                           const ::xml_schema::ro_string*);

      virtual bool
      _end_element_impl (const ::xml_schema::ro_string&,
                         const ::xml_schema::ro_string&);

      protected:
      ::sim_mob::conf::db_connection_pskel* connection_parser_;
    };

    class db_proc_groups_pskel: public ::xml_schema::complex_content
    {
      public:
      // Parser callbacks. Override them in your implementation.
      //
      // virtual void
      // pre ();

      virtual void
      proc_map ();

      virtual void
      post_db_proc_groups ();

      // Parser construction API.
      //
      void
      proc_map_parser (::sim_mob::conf::proc_map_pskel&);

      void
      parsers (::sim_mob::conf::proc_map_pskel& /* proc_map */);

      // Constructor.
      //
      db_proc_groups_pskel ();

      // Implementation.
      //
      protected:
      virtual bool
      _start_element_impl (const ::xml_schema::ro_string&,
                           const ::xml_schema::ro_string&,
                           const ::xml_schema::ro_string*);

      virtual bool
      _end_element_impl (const ::xml_schema::ro_string&,
                         const ::xml_schema::ro_string&);

      protected:
      ::sim_mob::conf::proc_map_pskel* proc_map_parser_;
    };
  }
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

#endif // CONF1_PSKEL_HPP
