package sim_mob.conf;

import java.awt.Color;
import java.util.Hashtable;

public class CssColorIdentifiers {
	
	/**
	 * Populate a hashtable with lowercase css color name/value pairs.
	 * @param IdentityColors
	 */
	public static void LoadIdentityColors(Hashtable<String, Color> IdentityColors) {
		IdentityColors.clear();
		IdentityColors.put("aliceblue", new Color(0xF0, 0xF8, 0xFF));
		IdentityColors.put("antiquewhite", new Color(0xFA, 0xEB, 0xD7));
		IdentityColors.put("aqua", new Color(0x00, 0xFF, 0xFF));
		IdentityColors.put("aquamarine", new Color(0x7F, 0xFF, 0xD4));
		IdentityColors.put("azure", new Color(0xF0, 0xFF, 0xFF));
		IdentityColors.put("beige", new Color(0xF5, 0xF5, 0xDC));
		IdentityColors.put("bisque", new Color(0xFF, 0xE4, 0xC4));
		IdentityColors.put("black", new Color(0x00, 0x00, 0x00));
		IdentityColors.put("blanchedalmond", new Color(0xFF, 0xEB, 0xCD));
		IdentityColors.put("blue", new Color(0x00, 0x00, 0xFF));
		IdentityColors.put("blueviolet", new Color(0x8A, 0x2B, 0xE2));
		IdentityColors.put("brown", new Color(0xA5, 0x2A, 0x2A));
		IdentityColors.put("burlywood", new Color(0xDE, 0xB8, 0x87));
		IdentityColors.put("cadetblue", new Color(0x5F, 0x9E, 0xA0));
		IdentityColors.put("chartreuse", new Color(0x7F, 0xFF, 0x00));
		IdentityColors.put("chocolate", new Color(0xD2, 0x69, 0x1E));
		IdentityColors.put("coral", new Color(0xFF, 0x7F, 0x50));
		IdentityColors.put("cornflowerblue", new Color(0x64, 0x95, 0xED));
		IdentityColors.put("cornsilk", new Color(0xFF, 0xF8, 0xDC));
		IdentityColors.put("crimson", new Color(0xDC, 0x14, 0x3C));
		IdentityColors.put("cyan", new Color(0x00, 0xFF, 0xFF));
		IdentityColors.put("darkblue", new Color(0x00, 0x00, 0x8B));
		IdentityColors.put("darkcyan", new Color(0x00, 0x8B, 0x8B));
		IdentityColors.put("darkgoldenrod", new Color(0xB8, 0x86, 0x0B));
		IdentityColors.put("darkgray", new Color(0xA9, 0xA9, 0xA9));
		IdentityColors.put("darkgrey", new Color(0xA9, 0xA9, 0xA9));
		IdentityColors.put("darkgreen", new Color(0x00, 0x64, 0x00));
		IdentityColors.put("darkkhaki", new Color(0xBD, 0xB7, 0x6B));
		IdentityColors.put("darkmagenta", new Color(0x8B, 0x00, 0x8B));
		IdentityColors.put("darkolivegreen", new Color(0x55, 0x6B, 0x2F));
		IdentityColors.put("darkorange", new Color(0xFF, 0x8C, 0x00));
		IdentityColors.put("darkorchid", new Color(0x99, 0x32, 0xCC));
		IdentityColors.put("darkred", new Color(0x8B, 0x00, 0x00));
		IdentityColors.put("darksalmon", new Color(0xE9, 0x96, 0x7A));
		IdentityColors.put("darkseagreen", new Color(0x8F, 0xBC, 0x8F));
		IdentityColors.put("darkslateblue", new Color(0x48, 0x3D, 0x8B));
		IdentityColors.put("darkslategray", new Color(0x2F, 0x4F, 0x4F));
		IdentityColors.put("darkslategrey", new Color(0x2F, 0x4F, 0x4F));
		IdentityColors.put("darkturquoise", new Color(0x00, 0xCE, 0xD1));
		IdentityColors.put("darkviolet", new Color(0x94, 0x00, 0xD3));
		IdentityColors.put("deeppink", new Color(0xFF, 0x14, 0x93));
		IdentityColors.put("deepskyblue", new Color(0x00, 0xBF, 0xFF));
		IdentityColors.put("dimgray", new Color(0x69, 0x69, 0x69));
		IdentityColors.put("dimgrey", new Color(0x69, 0x69, 0x69));
		IdentityColors.put("dodgerblue", new Color(0x1E, 0x90, 0xFF));
		IdentityColors.put("firebrick", new Color(0xB2, 0x22, 0x22));
		IdentityColors.put("floralwhite", new Color(0xFF, 0xFA, 0xF0));
		IdentityColors.put("forestgreen", new Color(0x22, 0x8B, 0x22));
		IdentityColors.put("fuchsia", new Color(0xFF, 0x00, 0xFF));
		IdentityColors.put("gainsboro", new Color(0xDC, 0xDC, 0xDC));
		IdentityColors.put("ghostwhite", new Color(0xF8, 0xF8, 0xFF));
		IdentityColors.put("gold", new Color(0xFF, 0xD7, 0x00));
		IdentityColors.put("goldenrod", new Color(0xDA, 0xA5, 0x20));
		IdentityColors.put("gray", new Color(0x80, 0x80, 0x80));
		IdentityColors.put("grey", new Color(0x80, 0x80, 0x80));
		IdentityColors.put("green", new Color(0x00, 0x80, 0x00));
		IdentityColors.put("greenyellow", new Color(0xAD, 0xFF, 0x2F));
		IdentityColors.put("honeydew", new Color(0xF0, 0xFF, 0xF0));
		IdentityColors.put("hotpink", new Color(0xFF, 0x69, 0xB4));
		IdentityColors.put("indianred", new Color(0xCD, 0x5C, 0x5C));
		IdentityColors.put("indigo", new Color(0x4B, 0x00, 0x82));
		IdentityColors.put("ivory", new Color(0xFF, 0xFF, 0xF0));
		IdentityColors.put("khaki", new Color(0xF0, 0xE6, 0x8C));
		IdentityColors.put("lavender", new Color(0xE6, 0xE6, 0xFA));
		IdentityColors.put("lavenderblush", new Color(0xFF, 0xF0, 0xF5));
		IdentityColors.put("lawngreen", new Color(0x7C, 0xFC, 0x00));
		IdentityColors.put("lemonchiffon", new Color(0xFF, 0xFA, 0xCD));
		IdentityColors.put("lightblue", new Color(0xAD, 0xD8, 0xE6));
		IdentityColors.put("lightcoral", new Color(0xF0, 0x80, 0x80));
		IdentityColors.put("lightcyan", new Color(0xE0, 0xFF, 0xFF));
		IdentityColors.put("lightgoldenrodyellow", new Color(0xFA, 0xFA, 0xD2));
		IdentityColors.put("lightgray", new Color(0xD3, 0xD3, 0xD3));
		IdentityColors.put("lightgrey", new Color(0xD3, 0xD3, 0xD3));
		IdentityColors.put("lightgreen", new Color(0x90, 0xEE, 0x90));
		IdentityColors.put("lightpink", new Color(0xFF, 0xB6, 0xC1));
		IdentityColors.put("lightsalmon", new Color(0xFF, 0xA0, 0x7A));
		IdentityColors.put("lightseagreen", new Color(0x20, 0xB2, 0xAA));
		IdentityColors.put("lightskyblue", new Color(0x87, 0xCE, 0xFA));
		IdentityColors.put("lightslategray", new Color(0x77, 0x88, 0x99));
		IdentityColors.put("lightslategrey", new Color(0x77, 0x88, 0x99));
		IdentityColors.put("lightsteelblue", new Color(0xB0, 0xC4, 0xDE));
		IdentityColors.put("lightyellow", new Color(0xFF, 0xFF, 0xE0));
		IdentityColors.put("lime", new Color(0x00, 0xFF, 0x00));
		IdentityColors.put("limegreen", new Color(0x32, 0xCD, 0x32));
		IdentityColors.put("linen", new Color(0xFA, 0xF0, 0xE6));
		IdentityColors.put("magenta", new Color(0xFF, 0x00, 0xFF));
		IdentityColors.put("maroon", new Color(0x80, 0x00, 0x00));
		IdentityColors.put("mediumaquamarine", new Color(0x66, 0xCD, 0xAA));
		IdentityColors.put("mediumblue", new Color(0x00, 0x00, 0xCD));
		IdentityColors.put("mediumorchid", new Color(0xBA, 0x55, 0xD3));
		IdentityColors.put("mediumpurple", new Color(0x93, 0x70, 0xD8));
		IdentityColors.put("mediumseagreen", new Color(0x3C, 0xB3, 0x71));
		IdentityColors.put("mediumslateblue", new Color(0x7B, 0x68, 0xEE));
		IdentityColors.put("mediumspringgreen", new Color(0x00, 0xFA, 0x9A));
		IdentityColors.put("mediumturquoise", new Color(0x48, 0xD1, 0xCC));
		IdentityColors.put("mediumvioletred", new Color(0xC7, 0x15, 0x85));
		IdentityColors.put("midnightblue", new Color(0x19, 0x19, 0x70));
		IdentityColors.put("mintcream", new Color(0xF5, 0xFF, 0xFA));
		IdentityColors.put("mistyrose", new Color(0xFF, 0xE4, 0xE1));
		IdentityColors.put("moccasin", new Color(0xFF, 0xE4, 0xB5));
		IdentityColors.put("navajowhite", new Color(0xFF, 0xDE, 0xAD));
		IdentityColors.put("navy", new Color(0x00, 0x00, 0x80));
		IdentityColors.put("oldlace", new Color(0xFD, 0xF5, 0xE6));
		IdentityColors.put("olive", new Color(0x80, 0x80, 0x00));
		IdentityColors.put("olivedrab", new Color(0x6B, 0x8E, 0x23));
		IdentityColors.put("orange", new Color(0xFF, 0xA5, 0x00));
		IdentityColors.put("orangered", new Color(0xFF, 0x45, 0x00));
		IdentityColors.put("orchid", new Color(0xDA, 0x70, 0xD6));
		IdentityColors.put("palegoldenrod", new Color(0xEE, 0xE8, 0xAA));
		IdentityColors.put("palegreen", new Color(0x98, 0xFB, 0x98));
		IdentityColors.put("paleturquoise", new Color(0xAF, 0xEE, 0xEE));
		IdentityColors.put("palevioletred", new Color(0xD8, 0x70, 0x93));
		IdentityColors.put("papayawhip", new Color(0xFF, 0xEF, 0xD5));
		IdentityColors.put("peachpuff", new Color(0xFF, 0xDA, 0xB9));
		IdentityColors.put("peru", new Color(0xCD, 0x85, 0x3F));
		IdentityColors.put("pink", new Color(0xFF, 0xC0, 0xCB));
		IdentityColors.put("plum", new Color(0xDD, 0xA0, 0xDD));
		IdentityColors.put("powderblue", new Color(0xB0, 0xE0, 0xE6));
		IdentityColors.put("purple", new Color(0x80, 0x00, 0x80));
		IdentityColors.put("red", new Color(0xFF, 0x00, 0x00));
		IdentityColors.put("rosybrown", new Color(0xBC, 0x8F, 0x8F));
		IdentityColors.put("royalblue", new Color(0x41, 0x69, 0xE1));
		IdentityColors.put("saddlebrown", new Color(0x8B, 0x45, 0x13));
		IdentityColors.put("salmon", new Color(0xFA, 0x80, 0x72));
		IdentityColors.put("sandybrown", new Color(0xF4, 0xA4, 0x60));
		IdentityColors.put("seagreen", new Color(0x2E, 0x8B, 0x57));
		IdentityColors.put("seashell", new Color(0xFF, 0xF5, 0xEE));
		IdentityColors.put("sienna", new Color(0xA0, 0x52, 0x2D));
		IdentityColors.put("silver", new Color(0xC0, 0xC0, 0xC0));
		IdentityColors.put("skyblue", new Color(0x87, 0xCE, 0xEB));
		IdentityColors.put("slateblue", new Color(0x6A, 0x5A, 0xCD));
		IdentityColors.put("slategray", new Color(0x70, 0x80, 0x90));
		IdentityColors.put("slategrey", new Color(0x70, 0x80, 0x90));
		IdentityColors.put("snow", new Color(0xFF, 0xFA, 0xFA));
		IdentityColors.put("springgreen", new Color(0x00, 0xFF, 0x7F));
		IdentityColors.put("steelblue", new Color(0x46, 0x82, 0xB4));
		IdentityColors.put("tan", new Color(0xD2, 0xB4, 0x8C));
		IdentityColors.put("teal", new Color(0x00, 0x80, 0x80));
		IdentityColors.put("thistle", new Color(0xD8, 0xBF, 0xD8));
		IdentityColors.put("tomato", new Color(0xFF, 0x63, 0x47));
		IdentityColors.put("turquoise", new Color(0x40, 0xE0, 0xD0));
		IdentityColors.put("violet", new Color(0xEE, 0x82, 0xEE));
		IdentityColors.put("wheat", new Color(0xF5, 0xDE, 0xB3));
		IdentityColors.put("white", new Color(0xFF, 0xFF, 0xFF));
		IdentityColors.put("whitesmoke", new Color(0xF5, 0xF5, 0xF5));
		IdentityColors.put("yellow", new Color(0xFF, 0xFF, 0x00));
		IdentityColors.put("yellowgreen", new Color(0x9A, 0xCD, 0x32));
	}

}

